config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :videos
  resources :countries

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/auth/facebook' => 'sessions#facebook'
  get '/auth/facebook/callback' => 'sessions#facebook'
  get '/logout' => 'sessions#destroy'
  post '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

  get '/countries' => 'countries#index'
  post '/countries' => 'countries#create'

 get '/countries/search' => 'countries#search'
 

  post '/players/age' => 'players#age' 
  post '/players/backhand' => 'players#backhand'  
  get '/players/filter' => 'players'
  post '/players/filter' => 'players#filter'
  get '/players/search' => 'players'
  post '/players/search' => 'players#search'
  get '/players' => 'players#index'
  post '/players' => 'players#index'
  get '/players/new' => 'players#new'
  post '/players/new' => 'players#create'
  get '/players/:slug/videos' => 'videos#index'
  get '/players/:slug/matches' => 'matches#index'
  get '/players/:slug/edit' => 'players#edit'
  post '/players/:slug/edit' => 'players#update'
  get '/players/:slug/delete' => 'players#destroy'
  get '/players/:slug/videos/new' => 'videos#new'
  post '/players/:slug/videos/new' => 'videos#create'
  get '/players/:slug/matches/new' => 'matches#new'
  post '/players/:slug/matches/new' => 'matches#create'
  get '/players/:slug/videos/:id/delete' => 'videos#destroy'
  post '/players/:slug/cancel' => 'videos#cancel'
  get '/players/:slug/videos/:id/edit' => 'videos#edit'
  post '/players/:slug/videos/:id/edit' => 'videos#update'
  get '/players/:slug/videos/:id/favorite' => 'videos#favorite'
  post '/players/:slug/videos/:id/favorite' => 'videos#favorite'
  post '/players/:slug/videos/:id/remove' => 'videos#remove'
  post '/players/:slug/videos' => 'players#cancel'
  
  post '/users/new' => 'users#create'
  get '/users/:slug' => 'users#show'
  get '/users/:slug/edit' => 'users#edit'
  post '/users/:slug/edit' => 'users#update'
  post '/users/:slug/edit/cancel' => 'users#cancel'
  get '/users/:slug/videos/:id/remove' => 'users#remove' #necessary - removing from users/show
  post '/users/:slug/videos/:id/remove' => 'users#remove' #necessary - removing from users/show
  get '/users/:slug/videos/:id/comment' => 'user_videos#comment'
  post '/users/:slug/videos/:id/comment' => 'user_videos#update'

  resources :players, only: [:show] do
    resources :matches, only: [:index, :new]
    resources :videos, only: [:index, :new]
  end
  
end

app/models/player.rb
class Player < ApplicationRecord
    has_one_attached :player_image

    validates_format_of :first_name, :last_name, :with => /\A[a-zA-Z]+\z/
    validates :sex_id, presence: true
    validates :birthdate, presence: true
    validates :feet, presence: true
    validates :inches, presence: true
    validates :country_id, presence: true
    validates :handedness_id, presence: true
    validates :forehand_grip_id, presence: true
    validates :backhand_type_id, presence: true
    validate :image_valid?
    
    belongs_to :sex, optional: true
    belongs_to :country, optional: true
    belongs_to :handedness, optional: true
    belongs_to :forehand_grip, optional: true
    belongs_to :backhand_type, optional: true

    has_many :videos
    has_many :categories, through: :videos
    has_many :player_styles
    has_many :styles, through: :player_styles
    has_many :player_matches
    has_many :matches, through: :player_matches
    accepts_nested_attributes_for :styles

    #scope :filter_by_criteria(attribute, id),

    scope :filter_by_forehand, -> (forehand_grip_id) {where forehand_grip_id: forehand_grip_id}

    scope :filter_by_backhand, -> (backhand_type_id) {where backhand_type_id: backhand_type_id}

    scope :filter_by_handedness, -> (handedness_id) {where handedness_id: handedness_id}

    scope :filter_by_sex, -> (sex_id) {where sex_id: sex_id}

    scope :filter_by_country, -> (country_id) {where country_id: country_id}
  
    scope :filter_by_first_name, -> (first_name){where first_name: first_name.capitalize}

    scope :filter_by_last_name, -> (last_name){where last_name: last_name.capitalize}

    # experimental scopes
    #scope :has_backhand_videos, ->{joins(:videos).where('category_id= 2')}

    #scope :older_than_30, ->{where('birthdate < ?', DateTime.now - 30.years)}

    # Player.joins(:videos).group("videos.id").order("count(videos.id) DESC")

    def styles_attributes=(style_attributes)
        style_attributes.values.each do |style_attribute|
            style = Style.find_or_create_by(style_attribute)
            self.styles << style
        end
    end

    def image_valid?
        if !player_image.attached?
            errors.add(:player_image, "is not attached")
        end
    end

    def slug
        [first_name.downcase, last_name.downcase].join("-")
    end

    def fullname
        [first_name, last_name].join(" ")
    end

    def unique_name?
        if Player.all.map{|player|player.fullname}.include?(fullname)
            errors.add(:player_name, "is already in this database")
        end
    end

    def self.find_by_slug(slug)
        self.all.find{|user| user.slug == slug}
    end

    def age
        now = Time.now.utc.to_date
        now.year - self.birthdate.year - (self.birthdate.to_date.change(:year => now.year) > now ? 1 : 0)
    end 

    def videos_count
        self.videos.count
    end

    def height_in_inches
        inches + feet*12
    end

    
    
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    before_action :require_login, :current_user
    before_action :all_players, :find_player 
    before_action :unauthorized_to_edit_player, only: [:edit]
    before_action :unauthorized_to_add_player, only: [:new]

    def index  
        instance_variable_players_sorted_by_name
        players_count
    end

    def filter

        @players=@players.filter_by_sex(params[:sex_id]) unless params[:sex_id].blank?

        @players=@players.filter_by_forehand(params[:forehand_grip_id]) unless params[:forehand_grip_id].blank?
        
        @players=@players.filter_by_backhand(params[:backhand_type_id]) unless params[:backhand_type_id].blank?

        @players=@players.filter_by_country(params[:country_id]) unless params[:country_id].blank?

        @players=@players.filter_by_handedness(params[:handedness_id]) unless params[:handedness_id].blank?

        instance_variable_players_sorted_by_name
        players_count
    end

    def backhand
        @players=Player.has_backhand_videos.uniq
        instance_variable_players_sorted_by_name
        players_count
        render :backhand
    end

    def age
        @players=Player.older_than_30
        instance_variable_players_sorted_by_name
        render :index
    end

    def search
        @players=@players.filter_by_first_name(params[:first_name]) unless params[:first_name].blank?

        @players=@players.filter_by_last_name(params[:last_name]) unless params[:last_name].blank?

        instance_variable_players_sorted_by_name
        players_count
        
    end 

    def match
    end

    def edit
    end

    def new
        @player=Player.new
    end

    def create
        @player=Player.new(player_params)
        if @player.save
            redirect_to "/players/#{@player.slug}/videos"
        else
            render :new 
        end       
    end

    def update
        if @player.update(player_params)
            redirect_to "/players/#{@player.slug}/videos"
        else 
            render :edit 
        end
    end

    def destroy
        @player.destroy
        redirect_to players_path
    end

    def cancel
        redirect_to "/players/#{@player.slug}/videos"
    end

    def cancel_new
        redirect_to "/players"
    end
        
    private

    def player_params
        params.require(:player).permit(:player_image, :first_name, :last_name, :sex_id, :birthdate, :country_id, :feet, :inches, :handedness_id, :forehand_grip_id, :backhand_type_id, style_ids:[], styles_attributes:[:name])
    end

    def unauthorized_to_edit_player
        redirect_to "/players/#{@player.slug}/videos" unless is_admin?
    end

    def unauthorized_to_add_player
        redirect_to "/players" unless is_admin?
    end

    def instance_variable_players_sorted_by_name
        @players_sorted_by_name = @players.sort_by{|p| p.first_name}
    end

    def players_count
        @players_count = @players.count
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_bio.html.erb
<div class="fixed-bio">

    <h1><%=@player.fullname%></h1> 

    <%=image_tag @player.player_image%> <br><br>

    <div class="player-country">
       <%=image_tag @player.country.flag_image, class: "show-flag"%> 
       <p><%=@player.country.name%></p>
    </div>

    <div class=player-details>
        <div class="first_row">
            <p><b>Age</b>: &nbsp;<%=@player.age%> &nbsp; | &nbsp;</p>
            <p><b>Height</b>: &nbsp;<%=@player.feet%>'<%=@player.inches%>" </p> 
        </div>
        <p><b>Handedness</b>: &nbsp;<%=@player.handedness.name%> </p>
        <p><b>Forehand</b>: &nbsp;<%=@player.forehand_grip.name%></p>
        <p><b>Backhand</b>: &nbsp;<%=@player.backhand_type.name%></p>
        <p><b>Play Style</b>:&nbsp; <%=@player.styles.uniq.map {|style| style.name}.join(", ")%></p>
    </div>

    <%if is_admin?%>
        <%=link_to "/players/#{@player.slug}/edit" do%>
            <p class="edit">edit player profile</p>
        <%end%> <br><br>
    <%end%>

</div>

app/views/players/_form.html.erb
<%= render partial: "layouts/errors", locals: {object: @player} %>
<!-- render the errors partial, send the @player as the 'object' -->

<div class="player-form">
    <%=form_for :player do |f|%>
        <p class="input-type">First Name</p>
        <%=f.text_field :first_name, class: "input-field", placeholder: "First Name", autocomplete: "off"%> <br><br>

        <p class="input-type">Last Name</p>
        <%=f.text_field :last_name, class: "input-field", placeholder: "Last Name"%>
        
         <br><br>

        
        <p class="input-type">Sex</p>
        <%=f.collection_select :sex_id, Sex.all, :id, :name, class: "input-field", include_blank: "Select Sex"%> <br><br>

        <p class="input-type">Birth Date</p>
        <%=f.date_field :birthdate, class: "input-field", placeholder: "MM/DD/YYYY"%> <br><br>

        <p class="input-type">Country</p>
        <%=f.collection_select :country_id, Country.all.order('name ASC'), :id, :name, class: "input-field", include_blank: "Select Country"%> <br><br>

        <p class="input-type">Height</p>
        <%=f.number_field :feet, class: "input-field-height", placeholder: "ft"%>&nbsp;'&nbsp;
        <%=f.number_field :inches, class: "input-field-height", placeholder: "in"%>&nbsp;"
        <br><br>

        <p class="input-type">Handedness</p>
        <%=f.collection_select :handedness_id, Handedness.all, :id, :name, class: "input-field", include_blank: "Select"%> <br><br>

        <p class="input-type">Forehand Grip</p>
        <%=f.collection_select :forehand_grip_id, ForehandGrip.all, :id, :name, class: "input-field", include_blank: "Select Forehand"%> <br><br>

        <p class="input-type">Backhand Type</p>
        <%=f.collection_select :backhand_type_id, BackhandType.all, :id, :name, class: "input-field", include_blank: "Select Backhand"%> <br><br>

        <p class="input-type">Play Style</p>
        <%=f.collection_check_boxes :style_ids, Style.all, :id, :name, class: "check-box", include_blank: ""%> <br><br>

        <!-- for adding submittable field for style 
        <%=f.fields_for :styles, @player.styles.build do |styles_fields|%>
            <%=styles_fields.text_field :name, placeholder: "Add Play Style"%>
        <%end%> <br><br>-->

        <p class="input-type">Player Photo</p>
        <%=f.file_field :player_image, class: "image-upload"%>
        
        <br><br><br>

        <%=f.submit 'Submit'%><br><br><br>

    <%end%>
</div>

app/views/players/_list.html.erb
<%=render 'application/header'%>

<div class="index-second-header">
    <h1>Players</h1>

    <%if is_admin?%>
        <%=link_to "Add Player","/players/new", class: "add-player" %> 
    <%end%>

    <div class="filter-input">
        <%=form_tag players_filter_path, :method=> 'post', :html=>{:class=>'form-inline'} do %>
            <div class="filter-menu">
                <%=select_tag :sex_id, options_for_select(Sex.show_by_name, selected: params[:sex_id]), :include_blank => 'All Sexes'%> <!--helper method in application_record.rb-->
            </div>
            <div class="filter-menu">
                <%=select_tag :handedness_id, options_for_select(Handedness.show_by_name, selected: params[:handedness_id]), :include_blank => 'All Handedness'%>
            </div>
            <div class="filter-menu">
                <%=select_tag :forehand_grip_id, options_for_select(ForehandGrip.show_by_name, selected: params[:forehand_grip_id]), :include_blank => 'All Forehands'%>
            </div>
            <div class = "filter-menu">
                <%=select_tag :backhand_type_id, options_for_select(BackhandType.show_by_name, selected: params[:backhand_type_id]), :include_blank => 'All Backhands'%>
            </div>
            <div class = "filter-menu">
                <%=select_tag :country_id, options_for_select(Country.sort_by_name, selected: params[:country_id]), :include_blank => 'All Countries'%>
            </div>

            <%=submit_tag("Filter")%>
        <%end%> <br><br>
    </div><!--filter-input-->

    <div class="name-filter filter-input">
        <%=form_tag players_search_path, :method=> 'post', :html=>{:class=>'form-inline'}, class: "search-bar" do %>
            <%=text_field_tag :first_name, params[:first_name], placeholder: "First Name"%>

            <%=text_field_tag :last_name, params[:last_name], placeholder: "Last Name"%>
            <%=submit_tag "Search", class:"search-input"%>
        <%end%>
    </div>

    <!--<%=form_tag players_backhand_path, :method=> 'post', class: "additional-scopes" do%>
        <%=submit_tag "Has Backhand Videos"%>
    <%end%>

    <%=form_tag players_age_path, :method=> 'post', class: "additional-scopes" do%>
        <%=submit_tag "Born After 1990"%>
    <%end%>-->




</div><!--index-second-header-->
<div class="search-separator"></div>

<div class="players-content">
    <h4><i><%=@players_count%> Players  </i></h4><br><br>
    <%@players_sorted_by_name.each do |player|%>
        <div class="player-card">
            <%=link_to "/players/#{player.slug}/videos" do%>
                <%=player.fullname%> 
                <%=image_tag player.country.flag_image, class: "index-flag"%> <br><br>
                <%=image_tag player.player_image, :class=>"player-index-img"%>
            <%end%>
        </div>
    <%end%> 
</div><!--players-content-->

app/views/players/backhand.html.erb
<%=render 'list'%>

app/views/players/edit.html.erb
<%=render 'application/header'%>

<div class="edit-page">
    <h3 class="form-header">Edit Player</h3> 

    <%=link_to "/players/#{@player.slug}/delete", :controller=>'players', :action=>'destroy' do%>
        <p>delete player profile</p>
    <%end%>
</div>

<%= render 'form'%>
<%=button_to "/players/#{@player.slug}/videos", :action=>'cancel', class: "cancel-player-button" do %>
    <p class="cancel-player">Cancel</p>
<%end%>

app/views/players/filter.html.erb
<%=render 'list'%>

app/views/players/index.html.erb
<%=render 'application/header'%>

<div class="index-second-header">
    <h1>Players</h1>

    <%if is_admin?%>
        <%=link_to "Add Player","/players/new", class: "add-player" %> 
    <%end%>

    <div class="filter-input">
        <%=form_tag players_filter_path, :method=> 'post', :html=>{:class=>'form-inline'} do %>
            <div class="filter-menu">
                <%=select_tag :sex_id,  options_for_select(Sex.all.collect{|f| [f.name, f.id]}, selected: params[:sex_id]), :include_blank => 'All Sexes'%>
            </div>
            <div class="filter-menu">
                <%=select_tag :handedness_id,  options_for_select(Handedness.all.collect{|f| [f.name, f.id]}, selected: params[:handedness_id]), :include_blank => 'All Handedness'%>
            </div>
            <div class="filter-menu">
                <%=select_tag :forehand_grip_id,  options_for_select(ForehandGrip.all.collect{|f| [f.name, f.id]}, selected: params[:forehand_grip_id]), :include_blank => 'All Forehands'%>
            </div>
            <div class = "filter-menu">
                <%=select_tag :backhand_type_id,  options_for_select(BackhandType.all.collect{|f| [f.name, f.id]}, selected: params[:backhand_type_id]), :include_blank => 'All Backhands'%>
            </div>
            <div class = "filter-menu">
                <%=select_tag :country_id,  options_for_select(Country.all.sort_by{|c| c.name}.collect{|f| [f.name, f.id]}, selected: params[:country_id]), :include_blank => 'All Countries'%>
            </div>

            <%=submit_tag("Filter")%>
        <%end%> <br><br>
    </div><!--filter-input-->

    <div class="name-filter filter-input">
        <%=form_tag players_search_path, :method=> 'post', :html=>{:class=>'form-inline'}, class: "search-bar" do %>
            <%=text_field_tag :first_name, params[:first_name], placeholder: "First Name"%>

            <%=text_field_tag :last_name, params[:last_name], placeholder: "Last Name"%>
            <%=submit_tag "Search", class:"search-input"%>
        <%end%>
    </div>
</div><!--index-second-header-->
<div class="search-separator"></div>

<div class="players-content">
    <h4><i><%=@players.count%> Players  </i></h4><br><br>
    <%players_sorted_by_name.each do |player|%>
        <div class="player-card">
            <%=link_to "/players/#{player.slug}/videos" do%>
                <%=player.fullname%> 
                <%=image_tag player.country.flag_image, class: "index-flag"%> <br><br>
                <%=image_tag player.player_image, :class=>"player-index-img"%>
            <%end%>
        </div>
    <%end%> 
</div><!--players-content-->

app/views/players/new.html.erb
<%=render 'application/header'%>

<h3 class="form-header">Add Player</h3>

<%= render 'form'%>
<%=button_to "/players", :action=>'cancel_new', class: "cancel-player-button" do %>
    <p class="cancel-player">Cancel</p>
<%end%>

app/views/players/search.html.erb
<%=render 'list'%>