config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :videos
  resources :countries

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/auth/facebook' => 'sessions#facebook'
  get '/auth/facebook/callback' => 'sessions#facebook'
  get '/logout' => 'sessions#destroy'
  post '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

  get '/countries' => 'countries#index'
  post '/countries' => 'countries#create'

 get '/countries/search' => 'countries#search'
 

  post '/players/age' => 'players#age' 
  post '/players/backhand' => 'players#backhand'  
  get '/players/filter' => 'players'
  post '/players/filter' => 'players#filter'
  get '/players/search' => 'players'
  post '/players/search' => 'players#search'
  get '/players' => 'players#index'
  post '/players' => 'players#index'
  get '/players/new' => 'players#new'
  post '/players/new' => 'players#create'
  get '/players/:slug/videos' => 'videos#index'
  get '/players/:slug/matches' => 'matches#index'
  get '/players/:slug/edit' => 'players#edit'
  post '/players/:slug/edit' => 'players#update'
  get '/players/:slug/delete' => 'players#destroy'
  get '/players/:slug/videos/new' => 'videos#new'
  post '/players/:slug/videos/new' => 'videos#create'
  get '/players/:slug/matches/new' => 'matches#new'
  post '/players/:slug/matches/new' => 'matches#create'
  get '/players/:slug/videos/:id/delete' => 'videos#destroy'
  post '/players/:slug/cancel' => 'videos#cancel'
  get '/players/:slug/videos/:id/edit' => 'videos#edit'
  post '/players/:slug/videos/:id/edit' => 'videos#update'
  get '/players/:slug/videos/:id/favorite' => 'videos#favorite'
  post '/players/:slug/videos/:id/favorite' => 'videos#favorite'
  post '/players/:slug/videos/:id/remove' => 'videos#remove'
  post '/players/:slug/videos' => 'players#cancel'
  
  post '/users/new' => 'users#create'
  get '/users/:slug' => 'users#show'
  get '/users/:slug/edit' => 'users#edit'
  post '/users/:slug/edit' => 'users#update'
  post '/users/:slug/edit/cancel' => 'users#cancel'
  get '/users/:slug/videos/:id/remove' => 'users#remove' #necessary - removing from users/show
  post '/users/:slug/videos/:id/remove' => 'users#remove' #necessary - removing from users/show
  get '/users/:slug/videos/:id/comment' => 'user_videos#comment'
  post '/users/:slug/videos/:id/comment' => 'user_videos#update'

  resources :players, only: [:show] do
    resources :matches, only: [:index, :new]
    resources :videos, only: [:index, :new]
  end
  
end

app/models/country.rb
class Country < ApplicationRecord
    has_one_attached :flag_image

    validates :name, presence: true

    def image_valid
        flag_image.attached?
    end

    scope :sort_by_name, -> {sort_by{|c| c.name}.collect{|f| [f.name, f.id]}}

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
    before_action :require_login

    def index
        @countries=Country.all 
    end

    def search
    end

    def create
        @country=Country.new(country_params)
      
        if @country.valid? && @country.image_valid
            @country.save
            redirect_to countries_path
        else
            render :index
        end       
    end

    private

    def country_params
        params.require(:country).permit(:flag_image, :name)
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/index.html.erb
<%=render 'application/header'%>

<div class="new-country-form">
    <%=form_for :country do |f|%>
        <h3 class="form-header">Add Country</h3>

        <p class="input-type">Country Name</p>
        <%=f.text_field :name, class: "input-field", placeholder: "Country Name"%> 

        <p class="input-type">Flag Image</p>
        <%=f.file_field :flag_image, class: "image-upload"%>

        <%=f.submit 'Submit'%>

        <p class="source-link"><i><a href="https://www.countries-ofthe-world.com/flags-of-the-world.html" target="_blank">Flag Sources</a></i></p>

    <%end%>
</div> <br><br>

<div class="flag-content">

    <h1>All Countries</h1>

    <%@countries.sort_by{|c| c.name}.each do |country|%>
        <div class="country-line">
            <%=image_tag country.flag_image, class: "flag-index-img"%>
            <p><%=country.name%> </p>
        </div>
    <%end%>
</div>

<%=form_tag countries_search_path, :method=> 'get' do%>
    <%=text_field_tag :search%>

    <%=submit_tag("Search Country")%>
<%end%>
    

app/views/countries/search.html.erb
<%=render 'index'%>